"""Quarantine file export — generate configs that test runners can consume to skip flaky tests."""

import json
from datetime import UTC, datetime

from flakydetector.models import FlakyTest


def _filter_by_action(tests: list[FlakyTest], actions: list[str] | None = None) -> list[FlakyTest]:
    """Filter tests by recommended action. Defaults to quarantine-only."""
    if actions is None:
        actions = ["quarantine"]
    return [t for t in tests if t.recommended_action in actions]


def export_pytest(flaky_tests: list[FlakyTest], *, actions: list[str] | None = None) -> str:
    """Generate a pytest conftest.py that skips quarantined tests.

    Usage: flaky-detect quarantine --format pytest > conftest_quarantine.py
    Then in CI: pytest --override-ini="conftest_quarantine.py"
    Or simply place it in the test directory.
    """
    filtered = _filter_by_action(flaky_tests, actions)
    timestamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        '"""Auto-generated quarantine list — skip known-flaky tests.',
        f"Generated by flaky-test-detector on {timestamp}",
        '"""',
        "",
        "import pytest",
        "",
        "QUARANTINED_TESTS = {",
    ]
    for t in filtered:
        lines.append(f'    "{t.test_name}",  # flakiness={t.flakiness_rate:.0%}')
    lines.append("}")
    lines.append("")
    lines.append("")
    lines.append("def pytest_collection_modifyitems(items):")
    lines.append('    """Skip tests that are quarantined due to flakiness."""')
    lines.append("    for item in items:")
    lines.append("        node_id = item.nodeid")
    lines.append("        for quarantined in QUARANTINED_TESTS:")
    lines.append("            if quarantined in node_id:")
    lines.append("                item.add_marker(")
    lines.append("                    pytest.mark.skip(")
    lines.append('                        reason=f"Quarantined: {quarantined} is flaky"')
    lines.append("                    )")
    lines.append("                )")
    lines.append("                break")
    lines.append("")

    return "\n".join(lines)


def export_junit(flaky_tests: list[FlakyTest], *, actions: list[str] | None = None) -> str:
    """Generate a JUnit/Maven/Gradle exclusion XML file.

    Usage: flaky-detect quarantine --format junit > quarantine-excludes.xml
    Gradle: test { exclude(file("quarantine-excludes.xml")) }
    Maven: <excludesFile>quarantine-excludes.xml</excludesFile>
    """
    filtered = _filter_by_action(flaky_tests, actions)
    timestamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")

    lines = [
        '<?xml version="1.0" encoding="UTF-8"?>',
        f"<!-- Auto-generated quarantine list — {timestamp} -->",
        "<excludes>",
    ]
    for t in filtered:
        # Convert FQN to path pattern: com.example.LoginTest.testTimeout → com/example/LoginTest
        parts = t.test_name.rsplit(".", 2)
        class_path = ".".join(parts[:-1]) if len(parts) >= 2 else t.test_name
        lines.append(f"  <exclude>{class_path}</exclude>")
    lines.append("</excludes>")
    lines.append("")

    return "\n".join(lines)


def export_json(flaky_tests: list[FlakyTest], *, actions: list[str] | None = None) -> str:
    """Generate a .quarantine.json file for generic consumption.

    Can be consumed by any CI system or custom test runner wrapper.
    """
    filtered = _filter_by_action(flaky_tests, actions)
    timestamp = datetime.now(UTC).strftime("%Y-%m-%d %H:%M:%S UTC")

    data = {
        "generated_at": timestamp,
        "generator": "flaky-test-detector",
        "quarantined_tests": [
            {
                "test_name": t.test_name,
                "flakiness_rate": t.flakiness_rate,
                "total_runs": t.total_runs,
                "pass_count": t.pass_count,
                "fail_count": t.fail_count,
                "action": t.recommended_action,
                "reason": f"Flakiness {t.flakiness_rate:.0%} over {t.total_runs} runs",
            }
            for t in filtered
        ],
    }
    return json.dumps(data, indent=2)
